import type { Metadata } from "next";
import "./globals.css";
import AuthContext from "@/context/AuthContext";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContext>
        <body className={`w-full overflow-auto flex flex-col`}>
          <header className="w-full flex justify-center bg-gray-900">
            <Navbar />
          </header>
          <main className="grow flex flex-col">{children}</main>
        </body>
      </AuthContext>
    </html>
  );
}
